# This is the main config file for CraftyCore
# This file is used to configure the plugin and its features
# If you need help with the configuration or have any questions join our discord server


# Enable in game warnings for plugin outdated versions
# This will send a warning to all players with a permission when the plugin is outdated and a new version is available
# Warnings are already sent to the console by default, this is non-configurable

# Teleports players to the spawn when they die
deathSpawn: true
# Teleports players to the spawn when they join
tpToSpawn: true

# Set with (/setspawn) and teleport to with (/spawn)
spawn.world:
spawn.x:
spawn.y:
spawn.z:











# MESSAGES
# This section is used to configure the messages sent by the plugin
# PREFIX is the prefix used in all messages
# You can use color codes in the messages
# You may use the default messages, but EVERY SINGLE MESSAGE IS CUSTOMIZABLE 
# You can find cool templates, premium and free, on our spigot page later. 
# Community made templates are also avalible
# If you want your template featured, just make a ticket in our discord 
Prefix: '&c&lCrafty&6&lCore &8» &7'
# This is the message sent to players when they get sent to spawn (/spawn)
spawnMessage: 'You have been sent to spawn!'
# This is the message sent to players when there is no spawn set (/setspawn)
noSpawnMessage: 'There is no spawn set! Please try again later!'
