# This is the main config file for CraftyCore
# This file is used to configure the plugin and its features
# If you need help with the configuration or have any questions join our discord server


# Enable in game warnings for plugin outdated versions
# This will send a warning to all players with a permission when the plugin is outdated and a new version is available
# Warnings are already sent to the console by default, this is non configurable
enableUpdateNotifications: true
